[tool.poetry]
name = "2024-06-16-practice"
version = "0.1.0"
description = ""
authors = ["Andrey Cheltyomov <master.haunt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
